### ISSUE TITLE
Consider swapping `Kw` for `coef_mix_hyp` in calibration runs

### ISSUE THREAD

**Issue by padilla410** [USGS-R/lake-temperature-missouri-models#3]
In the prior repo, I was avoiding calibrating with Kw because it was based on confident measurements. But you could do 

```r
# prep calibration parameters
cal_params <- c('cd','sw_factor','Kw')
cal_parscale <- c('cd' = 0.0001, 'sw_factor' = 0.02, 'Kw' = 0.05)
```

(or combine with the `names()` edit suggested below).

_Originally posted by @jread-usgs in https://github.com/USGS-R/lake-temperature-missouri-models/pull/2#discussion_r904109531_

**Comment by padilla410** [comment]
The addition of Kw makes sense, but I was surprised to see the removal of coef_hyp_mixing. Would you mind adding a little more context for this swap?

**Comment by jread-usgs** [comment]
Both parameters have an impact on how heat is distributed to lower waters. `coef_hyp_mixing` is a param that is related to the efficiency of deeper water mixing rates and has some lab and field values (and a recommended default). `Kw` impacts deeper water temperatures because it controls how rapidly the penetrative fraction of the sun's radiation attenuates with depth. So a clearer lake will allow more of that energy to reach and warm deep waters. A stained/turbid lake will end up translating a lot more of that energy into heating of the waters closer to the surface. I am supportive of using `coef_hyp_mixing` when there are clear issues with the prediction of deeper waters _but_ the value of `Kw` is known and we are confident in it (the rare cases where we estimate this using radiometers or very frequent/expert secchi measures or lab methods). 

But also in general, I don't recommend using more than three calibration parameters. Doing so gives the model too much flexibility and the likelihood of overfitting the calibration data (and doing poorly in independent periods that weren't in the calibration data) is too great.

**Comment by padilla410** [comment]
Sounds good. Thank you for the explanation.
